/*
 * DialogoSobre.java
 *
 * Created on 29 de Outubro de 2006, 12:57
 */

package br.edu.ufcg.ccc.ai.genetictsp.gui;

import java.awt.Graphics;
import javax.swing.ImageIcon;

/**
 *
 * @author Gustavo de Farias
 * @author Diego Renato
 * @author Helder Fernando
 */
public class AboutDialog extends javax.swing.JDialog {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private ImageIcon caixeiro;
    
    /** Creates new form DialogoSobre */
    public AboutDialog(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        
        this.caixeiro = new ImageIcon(this.getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/ts.jpg"));
        initComponents();
        this.setLocationRelativeTo(parent);
    }
    
    public void paint(Graphics g) {
        
        super.paint(g);
        Graphics g2 = this.painelFigura.getGraphics();
        
        this.caixeiro.paintIcon(this, g2, 0, 0);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoOK = new javax.swing.JButton();
        painelFigura = new javax.swing.JPanel();
        feitoPor = new javax.swing.JLabel();
        nome1 = new javax.swing.JLabel();
        nome2 = new javax.swing.JLabel();
        nome3 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        agradecimento = new javax.swing.JLabel();
        nome4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_about"); // NOI18N
        setTitle(bundle.getString("AD_window_title")); // NOI18N
        setModal(true);
        setResizable(false);

        botaoOK.setText("OK");
        this.getRootPane().setDefaultButton(this.botaoOK);
        botaoOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoOKActionPerformed(evt);
            }
        });

        painelFigura.setMaximumSize(new java.awt.Dimension(400, 100));
        painelFigura.setMinimumSize(new java.awt.Dimension(400, 100));
        painelFigura.setPreferredSize(new java.awt.Dimension(400, 100));

        org.jdesktop.layout.GroupLayout painelFiguraLayout = new org.jdesktop.layout.GroupLayout(painelFigura);
        painelFigura.setLayout(painelFiguraLayout);
        painelFiguraLayout.setHorizontalGroup(
            painelFiguraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );
        painelFiguraLayout.setVerticalGroup(
            painelFiguraLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        feitoPor.setText(bundle.getString("AD_feito_por")); // NOI18N

        nome1.setText("Diego Renato");

        nome2.setText("Helder Fernando");
        nome2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                nome2MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                nome2MouseExited(evt);
            }
        });

        nome3.setText("Gustavo de Farias");

        titulo.setFont(new java.awt.Font("Tahoma", 1, 14));
        titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        titulo.setText(bundle.getString("AD_title")); // NOI18N

        agradecimento.setText(bundle.getString("AD_orientacao")); // NOI18N

        nome4.setText("Joseana Macêdo Fechine");

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(painelFigura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(titulo, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 410, Short.MAX_VALUE)
                    .add(layout.createSequentialGroup()
                        .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, agradecimento, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, feitoPor, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .add(org.jdesktop.layout.GroupLayout.LEADING, layout.createSequentialGroup()
                                .add(10, 10, 10)
                                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, nome1, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, nome3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .add(org.jdesktop.layout.GroupLayout.LEADING, nome2, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 242, Short.MAX_VALUE))))
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 158, Short.MAX_VALUE)))
                .addContainerGap())
            .add(layout.createSequentialGroup()
                .add(20, 20, 20)
                .add(nome4, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE))
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .addContainerGap(336, Short.MAX_VALUE)
                .add(botaoOK, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 74, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(painelFigura, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(titulo)
                .add(28, 28, 28)
                .add(feitoPor)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nome1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nome2, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 14, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nome3)
                .add(18, 18, 18)
                .add(agradecimento)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(nome4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .add(botaoOK)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nome2MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nome2MouseExited
        
        this.nome2.setText("Helder Fernando");
    }//GEN-LAST:event_nome2MouseExited

    private void nome2MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_nome2MouseEntered
        
        this.nome2.setText("Helder \"pega fogo cabaré\" Fernando");
    }//GEN-LAST:event_nome2MouseEntered

    private void botaoOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoOKActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel agradecimento;
    private javax.swing.JButton botaoOK;
    private javax.swing.JLabel feitoPor;
    private javax.swing.JLabel nome1;
    private javax.swing.JLabel nome2;
    private javax.swing.JLabel nome3;
    private javax.swing.JLabel nome4;
    private javax.swing.JPanel painelFigura;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
    
}
