/*
 * MainFrame.java
 *
 * Created on 29 de Outubro de 2006, 11:50
 */

package br.edu.ufcg.ccc.ai.genetictsp.gui;

import java.awt.Cursor;
import java.awt.Image;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.IOException;
import java.io.PrintWriter;
import java.util.ArrayList;
import java.util.List;
import java.util.StringTokenizer;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileFilter;

import br.edu.ufcg.ccc.ai.genetictsp.genetic.GeneticAgent;
import br.edu.ufcg.ccc.ai.genetictsp.genetic.AgentIF;
import br.edu.ufcg.ccc.ai.genetictsp.utils.FileException;
import br.edu.ufcg.ccc.ai.genetictsp.utils.OpenMapFileFilter;
import br.edu.ufcg.ccc.ai.genetictsp.utils.SaveMapFileFilter;
import br.edu.ufcg.ccc.ai.genetictsp.utils.ParameterException;
import br.edu.ufcg.ccc.ai.genetictsp.utils.GraphicalPoint2D;
import br.edu.ufcg.ccc.ai.genetictsp.utils.Point2DIF;

/**
 *
 * @author Gustavo de Farias
 * @author Diego Renato
 * @author Helder Fernando
 */
public class MainFrame extends javax.swing.JFrame implements Runnable {
    
    /**
	 * 
	 */
	private static final long serialVersionUID = 1L;
	
	private List<Point2DIF> listaCidades;
    private AgentIF agente;

    private boolean executando;
    private boolean iniciado;
    private boolean pausa;

    private int countIteracoes;
    private int countMutacoes;
    private int countCruzamentos;
    private long countTempo;
    private int custoSolucaoAtual;

    private long tempoInicial;
    private int maximoIteracoes;
    
    private ImageIcon imgIniciar;
    private ImageIcon imgParar;
    
    /** Creates new form MainFrame */
    public MainFrame() {
        initComponents();
        this.setLocationRelativeTo(null);
        
        this.imgIniciar = new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/start.png"));
        this.imgParar = new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/stop.png"));
        
        this.iniciado = false;
        this.executando = false;
        this.pausa = true;
        
        this.listaCidades = new ArrayList<Point2DIF>();        
        this.painelCidades.setListaCidades(this.listaCidades);
    }
    
    public void run() {
        
        this.pausa = false;
        this.countIteracoes = 0;
                
        while (!this.pausa && (this.countIteracoes < this.maximoIteracoes)) {

            this.painelCidades.setTour(this.agente.realizaPasso());
            
            this.countIteracoes++;
            this.countCruzamentos = this.agente.getCruzamentos();
            this.countMutacoes = this.agente.getMutacoes();
            this.custoSolucaoAtual = this.agente.getCustoSolucaoAtual();
            this.atualizaTempo();
            
            this.atualizaInterface();
        }
        
        this.botaoIniciar.setEnabled(false);
        this.executando = false;
        this.alteraBotaoIniciar();
        this.desbloquearInterface();
        this.botaoIniciar.setEnabled(true);
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        fileChooserSalvar = new javax.swing.JFileChooser();
        fileChooserAbrir = new javax.swing.JFileChooser();
        painelCoordenadas = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelCidades = new javax.swing.JLabel();
        labelX = new javax.swing.JLabel();
        labelY = new javax.swing.JLabel();
        painelParametros = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        campoIteracoes = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        campoTamanhoPopulacao = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        checkBoxElitismo = new javax.swing.JCheckBox();
        campoMutacao = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        campoCruzamento = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        painelCidades = new br.edu.ufcg.ccc.ai.genetictsp.gui.MapPanel();
        painelExecucao = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        labelIteracoes = new javax.swing.JLabel();
        labelMutacoes = new javax.swing.JLabel();
        labelCustoSolucao = new javax.swing.JLabel();
        labelTempoDecorrido = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        labelCruzamentos = new javax.swing.JLabel();
        painelBotoes = new javax.swing.JPanel();
        botaoLimpar = new javax.swing.JButton();
        botaoIniciar = new javax.swing.JButton();
        jMenuBar1 = new javax.swing.JMenuBar();
        menuArquivo = new javax.swing.JMenu();
        itemNovo = new javax.swing.JMenuItem();
        itemAbrir = new javax.swing.JMenuItem();
        itemSalvar = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        itemSair = new javax.swing.JMenuItem();
        menuOpcoes = new javax.swing.JMenu();
        itemRestauraParametros = new javax.swing.JMenuItem();
        menuAjuda = new javax.swing.JMenu();
        itemAjuda = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JSeparator();
        itemSobre = new javax.swing.JMenuItem();

        fileChooserSalvar.setAcceptAllFileFilterUsed(false);
        fileChooserSalvar.setCurrentDirectory(getPastaInicial());
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings"); // NOI18N
        fileChooserSalvar.setDialogTitle(bundle.getString("MF_salvar_mapa")); // NOI18N
        fileChooserSalvar.setDialogType(javax.swing.JFileChooser.SAVE_DIALOG);
        fileChooserSalvar.setFileFilter(getFiltroArquivoSalvarMapa());
        fileChooserSalvar.setFileHidingEnabled(true);

        fileChooserAbrir.setAcceptAllFileFilterUsed(false);
        fileChooserAbrir.setCurrentDirectory(getPastaInicial());
        fileChooserAbrir.setDialogTitle(bundle.getString("MF_abrir_mapa")); // NOI18N
        fileChooserAbrir.setFileFilter(getFiltroArquivoAbrirMapa());
        fileChooserAbrir.setFileHidingEnabled(true);
        fileChooserAbrir.setForeground(java.awt.Color.white);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle(bundle.getString("MF_algoritmo_genetico_para_o_caixeiro_viajante")); // NOI18N
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(getIconImage());
        setName("mainFrame"); // NOI18N
        setResizable(false);

        painelCoordenadas.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setText("X =");

        jLabel2.setText("Y =");

        jLabel3.setText(bundle.getString("MF_cidades")); // NOI18N

        labelCidades.setText("0");

        org.jdesktop.layout.GroupLayout painelCoordenadasLayout = new org.jdesktop.layout.GroupLayout(painelCoordenadas);
        painelCoordenadas.setLayout(painelCoordenadasLayout);
        painelCoordenadasLayout.setHorizontalGroup(
            painelCoordenadasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painelCoordenadasLayout.createSequentialGroup()
                .addContainerGap()
                .add(jLabel3)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelCidades, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 91, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 271, Short.MAX_VALUE)
                .add(jLabel1)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelX, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel2)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelY, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 76, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        painelCoordenadasLayout.setVerticalGroup(
            painelCoordenadasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelCoordenadasLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                .add(jLabel3)
                .add(labelCidades)
                .add(labelY)
                .add(jLabel2)
                .add(labelX)
                .add(jLabel1))
        );

        painelParametros.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("MF_Configuracoes"))); // NOI18N

        jLabel4.setText(bundle.getString("MF_iteracoes2")); // NOI18N

        java.util.ResourceBundle bundle1 = java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters"); // NOI18N
        campoIteracoes.setText(bundle1.getString("defaultIteracoes")); // NOI18N
        campoIteracoes.setToolTipText(bundle.getString("MF_numero_maximo_de_iteracoes")); // NOI18N

        jLabel5.setText(bundle.getString("MF_populacao")); // NOI18N

        campoTamanhoPopulacao.setText(bundle1.getString("defaultPopulacao")); // NOI18N
        campoTamanhoPopulacao.setToolTipText(bundle.getString("MF_tamanho_da_populacao")); // NOI18N

        jLabel6.setText(bundle.getString("MF_mutacao")); // NOI18N

        jLabel7.setText("%");

        checkBoxElitismo.setSelected(getElitismoDefault());
        checkBoxElitismo.setText(bundle.getString("MF_elitismo")); // NOI18N
        checkBoxElitismo.setToolTipText(bundle.getString("MF_manutencao_da_melhor_solucao")); // NOI18N
        checkBoxElitismo.setBorder(javax.swing.BorderFactory.createEmptyBorder(0, 0, 0, 0));
        checkBoxElitismo.setMargin(new java.awt.Insets(0, 0, 0, 0));

        campoMutacao.setText(bundle1.getString("defaultMutacao")); // NOI18N
        campoMutacao.setToolTipText(bundle.getString("MF_probabilidade_de_mutacao")); // NOI18N

        jLabel12.setText(bundle.getString("MF_cruzamento")); // NOI18N

        campoCruzamento.setText(bundle1.getString("defaultCruzamento")); // NOI18N
        campoCruzamento.setToolTipText(bundle.getString("MF_probabilidade_de_cruzamento")); // NOI18N

        jLabel13.setText("%");

        org.jdesktop.layout.GroupLayout painelParametrosLayout = new org.jdesktop.layout.GroupLayout(painelParametros);
        painelParametros.setLayout(painelParametrosLayout);
        painelParametrosLayout.setHorizontalGroup(
            painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(campoIteracoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .add(painelParametrosLayout.createSequentialGroup()
                .add(jLabel5)
                .addContainerGap())
            .add(campoTamanhoPopulacao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 120, Short.MAX_VALUE)
            .add(painelParametrosLayout.createSequentialGroup()
                .add(jLabel6)
                .addContainerGap())
            .add(painelParametrosLayout.createSequentialGroup()
                .add(jLabel12)
                .addContainerGap(75, Short.MAX_VALUE))
            .add(painelParametrosLayout.createSequentialGroup()
                .add(painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, jLabel4)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, campoMutacao)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, campoCruzamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 75, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel7)
                    .add(jLabel13))
                .addContainerGap(30, Short.MAX_VALUE))
            .add(painelParametrosLayout.createSequentialGroup()
                .add(checkBoxElitismo)
                .addContainerGap())
        );
        painelParametrosLayout.setVerticalGroup(
            painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelParametrosLayout.createSequentialGroup()
                .add(jLabel4)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(campoIteracoes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel5)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(campoTamanhoPopulacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel6)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campoMutacao, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel7))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(jLabel12)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painelParametrosLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(campoCruzamento, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                    .add(jLabel13))
                .add(14, 14, 14)
                .add(checkBoxElitismo)
                .addContainerGap(65, Short.MAX_VALUE))
        );

        painelCidades.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                painelCidadesMouseMoved(evt);
            }
        });
        painelCidades.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                painelCidadesMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                painelCidadesMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                painelCidadesMousePressed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painelCidadesLayout = new org.jdesktop.layout.GroupLayout(painelCidades);
        painelCidades.setLayout(painelCidadesLayout);
        painelCidadesLayout.setHorizontalGroup(
            painelCidadesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 626, Short.MAX_VALUE)
        );
        painelCidadesLayout.setVerticalGroup(
            painelCidadesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 400, Short.MAX_VALUE)
        );

        painelExecucao.setBorder(javax.swing.BorderFactory.createTitledBorder(bundle.getString("MF_execucao"))); // NOI18N

        jLabel8.setText(bundle.getString("MF_iteracoes")); // NOI18N
        jLabel8.setToolTipText(bundle.getString("MF_numero_de_iteracoes_concluidas")); // NOI18N

        jLabel9.setText(bundle.getString("MF_mutacoes")); // NOI18N
        jLabel9.setToolTipText(bundle.getString("MF_mutacoes_ocorridas")); // NOI18N

        jLabel10.setText(bundle.getString("MF_custo_da_melhor_solucao")); // NOI18N
        jLabel10.setToolTipText(bundle.getString("MF_custo_da_solucao_atualmente_mostrada")); // NOI18N

        jLabel11.setText(bundle.getString("MF_tempo_decorrido")); // NOI18N
        jLabel11.setToolTipText(bundle.getString("MF_tempo_de_execucao_do_algoritmo")); // NOI18N

        labelIteracoes.setToolTipText(bundle.getString("MF_numero_de_iteracoes_concluidas")); // NOI18N

        labelMutacoes.setToolTipText(bundle.getString("MF_mutacoes_ocorridas")); // NOI18N

        labelCustoSolucao.setToolTipText(bundle.getString("MF_custo_da_solucao_atualmente_mostrada")); // NOI18N

        labelTempoDecorrido.setToolTipText(bundle.getString("MF_tempo_de_execucao_do_algoritmo")); // NOI18N

        jLabel14.setText(bundle.getString("MF_cruzamentos")); // NOI18N
        jLabel14.setToolTipText(bundle.getString("MF_cruzamentos_efetuados")); // NOI18N

        labelCruzamentos.setToolTipText(bundle.getString("MF_cruzamentos_efetuados2")); // NOI18N

        org.jdesktop.layout.GroupLayout painelExecucaoLayout = new org.jdesktop.layout.GroupLayout(painelExecucao);
        painelExecucao.setLayout(painelExecucaoLayout);
        painelExecucaoLayout.setHorizontalGroup(
            painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelExecucaoLayout.createSequentialGroup()
                .add(painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, painelExecucaoLayout.createSequentialGroup()
                        .add(jLabel11)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelTempoDecorrido, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(org.jdesktop.layout.GroupLayout.LEADING, painelExecucaoLayout.createSequentialGroup()
                        .add(jLabel8)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelIteracoes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 130, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(31, 31, 31)
                .add(painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING, false)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, painelExecucaoLayout.createSequentialGroup()
                        .add(jLabel9)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelMutacoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(painelExecucaoLayout.createSequentialGroup()
                        .add(jLabel14)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(labelCruzamentos, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 121, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .add(27, 27, 27)
                .add(jLabel10)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(labelCustoSolucao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 236, Short.MAX_VALUE))
        );
        painelExecucaoLayout.setVerticalGroup(
            painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(painelExecucaoLayout.createSequentialGroup()
                .add(painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(jLabel10)
                    .add(jLabel9)
                    .add(labelIteracoes)
                    .add(labelMutacoes)
                    .add(labelCustoSolucao))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painelExecucaoLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel11)
                    .add(jLabel14)
                    .add(labelTempoDecorrido)
                    .add(labelCruzamentos)))
        );

        painelBotoes.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        botaoLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/new.png"))); // NOI18N
        botaoLimpar.setMnemonic('L');
        botaoLimpar.setText(bundle.getString("MF_limpar")); // NOI18N
        botaoLimpar.setEnabled(false);
        botaoLimpar.setPreferredSize(new java.awt.Dimension(63, 23));
        botaoLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoLimparActionPerformed(evt);
            }
        });

        botaoIniciar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/start.png"))); // NOI18N
        botaoIniciar.setMnemonic('I');
        botaoIniciar.setText(bundle.getString("MF_iniciar")); // NOI18N
        botaoIniciar.setEnabled(false);
        this.getRootPane().setDefaultButton(this.botaoIniciar);
        botaoIniciar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoIniciarActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout painelBotoesLayout = new org.jdesktop.layout.GroupLayout(painelBotoes);
        painelBotoes.setLayout(painelBotoesLayout);
        painelBotoesLayout.setHorizontalGroup(
            painelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(botaoLimpar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
            .add(botaoIniciar, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 132, Short.MAX_VALUE)
        );
        painelBotoesLayout.setVerticalGroup(
            painelBotoesLayout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, painelBotoesLayout.createSequentialGroup()
                .add(botaoIniciar)
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED, 38, Short.MAX_VALUE)
                .add(botaoLimpar, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 37, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
        );

        menuArquivo.setMnemonic('A');
        menuArquivo.setText(bundle.getString("MF_arquivo")); // NOI18N

        itemNovo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/new.png"))); // NOI18N
        itemNovo.setMnemonic('N');
        itemNovo.setText(bundle.getString("MF_novo_mapa")); // NOI18N
        itemNovo.setEnabled(false);
        itemNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNovoActionPerformed(evt);
            }
        });
        menuArquivo.add(itemNovo);

        itemAbrir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/open.png"))); // NOI18N
        itemAbrir.setMnemonic('b');
        itemAbrir.setText(bundle.getString("MF_abrir_mapa")); // NOI18N
        itemAbrir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAbrirActionPerformed(evt);
            }
        });
        menuArquivo.add(itemAbrir);

        itemSalvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/save.png"))); // NOI18N
        itemSalvar.setMnemonic('r');
        itemSalvar.setText(bundle.getString("MF_salvar_mapa")); // NOI18N
        itemSalvar.setEnabled(false);
        itemSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSalvarActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSalvar);
        menuArquivo.add(jSeparator2);

        itemSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/quit.png"))); // NOI18N
        itemSair.setMnemonic('S');
        itemSair.setText(bundle.getString("MF_sair")); // NOI18N
        itemSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSairActionPerformed(evt);
            }
        });
        menuArquivo.add(itemSair);

        jMenuBar1.add(menuArquivo);

        menuOpcoes.setMnemonic('O');
        menuOpcoes.setText(bundle.getString("MF_opcoes")); // NOI18N

        itemRestauraParametros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/restore.png"))); // NOI18N
        itemRestauraParametros.setMnemonic('R');
        itemRestauraParametros.setText(bundle.getString("MF_restaurar_configuracao")); // NOI18N
        itemRestauraParametros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemRestauraParametrosActionPerformed(evt);
            }
        });
        menuOpcoes.add(itemRestauraParametros);

        jMenuBar1.add(menuOpcoes);

        menuAjuda.setMnemonic('u');
        menuAjuda.setText(bundle.getString("MF_ajuda")); // NOI18N

        itemAjuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/help.png"))); // NOI18N
        itemAjuda.setMnemonic('C');
        itemAjuda.setText(bundle.getString("MF_conteudo")); // NOI18N
        itemAjuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemAjudaActionPerformed(evt);
            }
        });
        menuAjuda.add(itemAjuda);
        menuAjuda.add(jSeparator1);

        itemSobre.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/about.png"))); // NOI18N
        itemSobre.setMnemonic('S');
        itemSobre.setText(bundle.getString("MF_sobre")); // NOI18N
        itemSobre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemSobreActionPerformed(evt);
            }
        });
        menuAjuda.add(itemSobre);

        jMenuBar1.add(menuAjuda);

        setJMenuBar(jMenuBar1);

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING)
                    .add(org.jdesktop.layout.GroupLayout.LEADING, painelCoordenadas, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(painelCidades, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.TRAILING, false)
                    .add(painelBotoes, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .add(painelParametros, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .add(painelExecucao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .add(painelParametros, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(painelBotoes, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, layout.createSequentialGroup()
                        .add(painelCidades, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                        .add(painelCoordenadas, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.RELATED)
                .add(painelExecucao, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void itemAbrirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAbrirActionPerformed
        
        try {
            int resp = this.fileChooserAbrir.showOpenDialog(this);
            
            if (resp == JFileChooser.CANCEL_OPTION) {                
                return;
            }
        
            if (resp == JFileChooser.ERROR_OPTION) {                
                throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_de_mapa_invalido"));
            }
            
            if (resp == JFileChooser.APPROVE_OPTION) {
                
                File f = this.fileChooserAbrir.getSelectedFile();
                
                if (f.exists()) {
                    
                    if (f.isFile() && f.canRead() && !f.isHidden() && f.getName().toLowerCase().endsWith(".tsm")) {
                        
                        this.abreCidades(f);
                    }
                    else {
                        throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_protegido_ou_invalido1"));
                    }
                }
                else {
                    throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_inexistente"));
                }
            }
        }
        catch (FileException ae) {
            
            JOptionPane.showMessageDialog(this, ae.getMessage(), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_carregamento1"), JOptionPane.ERROR_MESSAGE);            
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_inesperado_no_carregamento"), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_carregamento2"), JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_itemAbrirActionPerformed

    private void itemSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSalvarActionPerformed
        
        try {
            
            int resp = this.fileChooserSalvar.showSaveDialog(this);
            
            if (resp == JFileChooser.CANCEL_OPTION) {                
                return;
            }
        
            if (resp == JFileChooser.ERROR_OPTION) {                
                throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_de_salvamento_invalido"));
            }
            
            if (resp == JFileChooser.APPROVE_OPTION) {
                
                File f = this.fileChooserSalvar.getSelectedFile();
                
                if (f.exists()) {
                    
                    if (f.isFile() && f.canWrite() && !f.isHidden() && f.getName().toLowerCase().endsWith(".tsm")) {
                        
                        this.salvaCidades(f);
                    }
                    else {                        
                        throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_protegido_ou_invalido2"));
                    }
                }
                else {
                    
                    if (f.getName().toLowerCase().endsWith(".tsm")) {
                        
                        this.salvaCidades(f);
                    }
                    else {
                        throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_nome_de_arquivo_invalido"));
                    }
                }
            }
        }
        catch (FileException ae) {
            
            JOptionPane.showMessageDialog(this, ae.getMessage(), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_salvamento1"), JOptionPane.ERROR_MESSAGE);            
        }
        catch (Exception e) {
            
            JOptionPane.showMessageDialog(this, java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_inesperado_no_salvamento"), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_salvamento2"), JOptionPane.ERROR_MESSAGE);            
        }
    }//GEN-LAST:event_itemSalvarActionPerformed

    private void itemRestauraParametrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemRestauraParametrosActionPerformed
        
        this.restauraParametros();
    }//GEN-LAST:event_itemRestauraParametrosActionPerformed

    private void itemNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNovoActionPerformed
        
        this.botaoLimparActionPerformed(evt);
    }//GEN-LAST:event_itemNovoActionPerformed
  
    private void botaoIniciarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoIniciarActionPerformed
        
        // não iniciado
        if (!this.iniciado) {
            
            this.iniciar();
        }
        // iniciado
        else {
            // executando
            if (this.executando) {
                
                this.parar();
            }
            // interrompido
            else {
                
                this.continuar();
            }
        }        
    }//GEN-LAST:event_botaoIniciarActionPerformed

    private void botaoLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoLimparActionPerformed

        this.botaoIniciar.setEnabled(false);
        this.botaoLimpar.setEnabled(false);
        this.itemNovo.setEnabled(false);
        this.itemSalvar.setEnabled(false);
        
        this.painelCidades.modoInicializacao();
        
        this.iniciado = false;
        this.agente = null;
        
        this.resetaCidades();
        this.atualizaInterface();
    }//GEN-LAST:event_botaoLimparActionPerformed

    private void resetaCidades() {
        
        this.listaCidades.clear();
    }
    
    private void painelCidadesMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCidadesMousePressed
        
        // se está rodando não pode adicionar cidades ao mapa
        if (this.iniciado && this.executando) {            
            return;
        }
        
        if (this.iniciado) {
            
            this.painelCidades.modoInicializacao();
            
            this.iniciado = false;
            this.agente = null;
        }
        
        this.listaCidades.add( new GraphicalPoint2D(evt.getPoint()) );
        this.atualizaInterface();
        
        this.botaoLimpar.setEnabled(true);
        this.itemNovo.setEnabled(true);
        this.itemSalvar.setEnabled(true);
        if (this.listaCidades.size() >= 4) {
            
            this.botaoIniciar.setEnabled(true);
        }
    }//GEN-LAST:event_painelCidadesMousePressed

    private int getNumCidades() {      
        return this.listaCidades.size();
    }
    
    private void painelCidadesMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCidadesMouseEntered
        
        if (!this.iniciado || !this.executando) {
            
            this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
        }
    }//GEN-LAST:event_painelCidadesMouseEntered

    private void itemAjudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemAjudaActionPerformed
        
        new HelpDialog(this, true).setVisible(true);
    }//GEN-LAST:event_itemAjudaActionPerformed

    private void itemSobreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSobreActionPerformed
        
       new AboutDialog(this, true).setVisible(true);        
    }//GEN-LAST:event_itemSobreActionPerformed

    private void painelCidadesMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCidadesMouseExited
        
        this.setCursor(Cursor.getDefaultCursor());
        
        this.labelX.setText("");
        this.labelY.setText("");
    }//GEN-LAST:event_painelCidadesMouseExited

    private void painelCidadesMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_painelCidadesMouseMoved
        
        if (!this.iniciado || !this.executando) {
            
            this.setCursor(Cursor.getPredefinedCursor(Cursor.CROSSHAIR_CURSOR));
            this.labelX.setText("" + evt.getX());
            this.labelY.setText("" + evt.getY());
        }        
    }//GEN-LAST:event_painelCidadesMouseMoved

    private void itemSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemSairActionPerformed
        
        System.exit(0);
    }//GEN-LAST:event_itemSairActionPerformed

    private void atualizaInterface() {
        
        this.repaint();
        this.painelCidades.repaint();
        this.labelCidades.setText("" + this.getNumCidades());
        
        if (this.iniciado) {
            
            this.labelCustoSolucao.setText("" + this.custoSolucaoAtual);
            this.labelIteracoes.setText("" + this.countIteracoes);
            this.labelMutacoes.setText("" + this.countMutacoes);
            this.labelTempoDecorrido.setText(this.countTempo + java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_seconds"));
            this.labelCruzamentos.setText("" + this.countCruzamentos);
        }
        else {
            this.labelCustoSolucao.setText("");
            this.labelIteracoes.setText("");
            this.labelMutacoes.setText("");
            this.labelTempoDecorrido.setText("");
            this.labelCruzamentos.setText("");
        }
    }

    private synchronized void iniciar() {
                
        this.botaoIniciar.setEnabled(false);
        this.tempoInicial = System.currentTimeMillis();
        this.bloqueiaInterface();
        
        int populacao;
        int mutacao;
        int cruzamento;
        boolean elitismo;
        
        try {
            this.setMaximoIteracoes();
            
            populacao = this.getParametroPopulacao();
            mutacao = this.getParametroMutacao();
            cruzamento = this.getParametroCruzamento();
            elitismo = this.getParametroElitismo();            
        }
        catch (ParameterException pe) {
            
            JOptionPane.showMessageDialog(this, pe.getMessage(), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_parametro1"), JOptionPane.ERROR_MESSAGE);
            
            this.botaoIniciar.setEnabled(true);
            this.desbloquearInterface();
            return;
        }
        
        this.agente = new GeneticAgent(this.listaCidades, populacao, mutacao, cruzamento, elitismo);
        this.iniciado = true;
        
        this.painelCidades.modoExecucao();
        
        Thread t = new Thread(this);
        t.start();
        
        this.executando = true;
        
        this.alteraBotaoParar();
        this.botaoIniciar.setEnabled(true);
    }

    private synchronized void parar() {
        
        this.botaoIniciar.setEnabled(false);
        this.pausa = true;
    }

    private synchronized void continuar() {
                
        this.botaoIniciar.setEnabled(false);
        this.tempoInicial = System.currentTimeMillis();
        this.bloqueiaInterface();
        
        int populacao;
        int mutacao;
        int cruzamento;
        boolean elitismo;
        
        try {
            this.setMaximoIteracoes();
            
            populacao = this.getParametroPopulacao();
            mutacao = this.getParametroMutacao();
            cruzamento = this.getParametroCruzamento();
            elitismo = this.getParametroElitismo();
        }
        catch (ParameterException pe) {
            
            JOptionPane.showMessageDialog(this, pe.getMessage(), java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_no_parametro2"), JOptionPane.ERROR_MESSAGE);
            
            this.botaoIniciar.setEnabled(true);
            this.desbloquearInterface();
            return;
        }
        
        this.agente.resetaParametros(populacao, mutacao, cruzamento, elitismo);
        
        Thread t = new Thread(this);
        t.start();
        
        this.executando = true;
        
        this.alteraBotaoParar();
        this.botaoIniciar.setEnabled(true);
    }

    private void bloqueiaInterface() {
        
        this.botaoLimpar.setEnabled(false);
        
        this.menuOpcoes.setEnabled(false);
        this.menuAjuda.setEnabled(false);
        this.itemAbrir.setEnabled(false);
        this.itemNovo.setEnabled(false);
        this.itemSalvar.setEnabled(false);
        
        this.bloqueiaPainelParametros();
    }

    private void desbloquearInterface() {
        
        this.botaoLimpar.setEnabled(true);
        
        this.menuOpcoes.setEnabled(true);
        this.menuAjuda.setEnabled(true);
        this.itemAbrir.setEnabled(true);
        this.itemNovo.setEnabled(true);
        this.itemSalvar.setEnabled(true);
        
        this.desbloqueiaPainelParametros();
    }

    private void bloqueiaPainelParametros() {
        
        this.campoIteracoes.setEnabled(false);
        this.campoTamanhoPopulacao.setEnabled(false);
        this.campoMutacao.setEnabled(false);
        this.campoCruzamento.setEnabled(false);
        this.checkBoxElitismo.setEnabled(false);     
    }

    private void desbloqueiaPainelParametros() {
        
        this.campoIteracoes.setEnabled(true);
        this.campoTamanhoPopulacao.setEnabled(true);
        this.campoMutacao.setEnabled(true);
        this.campoCruzamento.setEnabled(true);
        this.checkBoxElitismo.setEnabled(true);     
    }
    
    private void restauraParametros() {
        
        this.campoIteracoes.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters").getString("defaultIteracoes"));
        this.campoTamanhoPopulacao.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters").getString("defaultPopulacao"));
        this.campoMutacao.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters").getString("defaultMutacao"));
        this.campoCruzamento.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters").getString("defaultCruzamento"));

        this.checkBoxElitismo.setSelected(this.getElitismoDefault());
    }

    private int getParametroPopulacao() throws ParameterException {
        
         try {
            int v = Integer.parseInt(this.campoTamanhoPopulacao.getText().trim());
            
            if (v < 2) {
                throw new Exception();
            }
            
            return v;
        }        
        catch (Exception e) {
            
            throw new ParameterException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_tamanho_da_populacao_invalido"));
        }
    }

    private int getParametroMutacao() throws ParameterException {
        
         try {
            int v = Integer.parseInt(this.campoMutacao.getText().trim());
            
            if (v < 0 || v > 100) {
                throw new Exception();
            }
            
            return v;
        }        
        catch (Exception e) {
            
            throw new ParameterException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_porcentagem_de_mutacao_invalida"));
        }
    }
    
    private int getParametroCruzamento()  throws ParameterException {
        
        try {
            int v = Integer.parseInt(this.campoCruzamento.getText().trim());
            
            if (v < 0 || v > 100) {
                throw new Exception();
            }
            
            return v;
        }        
        catch (Exception e) {
            
            throw new ParameterException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_porcentagem_de_cruzamento_invalida"));
        }
    }
    
    private FileFilter getFiltroArquivoAbrirMapa() {
        
        return new OpenMapFileFilter();
    }
    
    private FileFilter getFiltroArquivoSalvarMapa() {
        
        return new SaveMapFileFilter();
    }
    
    private File getPastaInicial() {
        
        return new File("./maps");
    }
    
    public Image getIconImage() {
        
        return new ImageIcon(this.getClass().getResource("/br/edu/ufcg/ccc/ai/genetictsp/gui/images/city.png")).getImage();
    }

    private boolean getElitismoDefault() {

        return Boolean.parseBoolean(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/parameters").getString("defaultElitismo"));
    }

    private boolean getParametroElitismo() {
       
        return this.checkBoxElitismo.isSelected();
    }

    private void setMaximoIteracoes() throws ParameterException {
        
        try {
            int v = Integer.parseInt(this.campoIteracoes.getText().trim());
            
            if (v <= 0) {
                throw new Exception();
            }
            
            this.maximoIteracoes = v;
        }
        catch (Exception e) {
            
            throw new ParameterException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_numero_de_iteracoes_invalido"));
        }
    }

    private void atualizaTempo() {
        
        this.countTempo = (System.currentTimeMillis() - this.tempoInicial) / 1000;
    }

    private void salvaCidades(File f) throws FileException {
        
        PrintWriter pw = null;
        try {
            pw = new PrintWriter(f);
            
            for (Point2DIF p : this.listaCidades) {
                
                pw.println(p.getX() + ";" + p.getY());
            }
            pw.flush();
        }
        catch (FileNotFoundException ex) {
            throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_ao_escrever_no_arquivo"));
        }
        finally {
            if (pw != null) {
                pw.close();
            }
        }        
    }

    private void abreCidades(File f) throws FileException, IOException {
        
        BufferedReader br = null;
        try {
            List<Point2DIF> novaLista = new ArrayList<Point2DIF>();
            
            br = new BufferedReader(new FileReader(f));
            
            String linha = "";
            while ((linha = br.readLine()) != null) {

                StringTokenizer st = new StringTokenizer(linha, ";");
                
                novaLista.add( new GraphicalPoint2D( Integer.parseInt(st.nextToken()), Integer.parseInt(st.nextToken()) ) );
            }
            
            if (novaLista.size() > 0) {

                if (this.iniciado) {
            
                    this.painelCidades.modoInicializacao();
            
                    this.iniciado = false;
                    this.agente = null;
                }
        
                this.listaCidades.clear();
                this.listaCidades.addAll(novaLista);
                this.atualizaInterface();
                
                this.botaoLimpar.setEnabled(true);
                this.itemNovo.setEnabled(true);
                this.itemSalvar.setEnabled(true);
                if (this.listaCidades.size() >= 4) {
                    
                    this.botaoIniciar.setEnabled(true);
                }
            }
            else {
                throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_arquivo_vazio"));
            }
        }  
        catch (Exception e) {
            
            if (e instanceof FileException) {
                throw (FileException)e;
            }
            
            throw new FileException(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_erro_na_leitura_do_arquivo"));
        }
        finally {
            if (br != null) {
                br.close();
            }
        }
    }

    private void alteraBotaoParar() {
        
        this.botaoIniciar.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_parar"));
        this.botaoIniciar.setMnemonic('P');
        this.botaoIniciar.setIcon(this.imgParar);
    }
    
    private void alteraBotaoIniciar() {
        
        this.botaoIniciar.setText(java.util.ResourceBundle.getBundle("br/edu/ufcg/ccc/ai/genetictsp/gui/resources/local_strings").getString("MF_iniciar"));
        this.botaoIniciar.setMnemonic('I');
        this.botaoIniciar.setIcon(this.imgIniciar);
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoIniciar;
    private javax.swing.JButton botaoLimpar;
    private javax.swing.JTextField campoCruzamento;
    private javax.swing.JTextField campoIteracoes;
    private javax.swing.JTextField campoMutacao;
    private javax.swing.JTextField campoTamanhoPopulacao;
    private javax.swing.JCheckBox checkBoxElitismo;
    private javax.swing.JFileChooser fileChooserAbrir;
    private javax.swing.JFileChooser fileChooserSalvar;
    private javax.swing.JMenuItem itemAbrir;
    private javax.swing.JMenuItem itemAjuda;
    private javax.swing.JMenuItem itemNovo;
    private javax.swing.JMenuItem itemRestauraParametros;
    private javax.swing.JMenuItem itemSair;
    private javax.swing.JMenuItem itemSalvar;
    private javax.swing.JMenuItem itemSobre;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel labelCidades;
    private javax.swing.JLabel labelCruzamentos;
    private javax.swing.JLabel labelCustoSolucao;
    private javax.swing.JLabel labelIteracoes;
    private javax.swing.JLabel labelMutacoes;
    private javax.swing.JLabel labelTempoDecorrido;
    private javax.swing.JLabel labelX;
    private javax.swing.JLabel labelY;
    private javax.swing.JMenu menuAjuda;
    private javax.swing.JMenu menuArquivo;
    private javax.swing.JMenu menuOpcoes;
    private javax.swing.JPanel painelBotoes;
    private br.edu.ufcg.ccc.ai.genetictsp.gui.MapPanel painelCidades;
    private javax.swing.JPanel painelCoordenadas;
    private javax.swing.JPanel painelExecucao;
    private javax.swing.JPanel painelParametros;
    // End of variables declaration//GEN-END:variables

}
